/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:2860bfa8-a10a-4a86-8358-da103c2015fe",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_v2Di6g6xa",
    "aws_user_pools_web_client_id": "5mlgv8pd70uhtfbf5q5vdld6qn",
    "oauth": {}
};


export default awsmobile;
